### PR TITLE
Permutation shuffle test attempt

### PR DESCRIPTION
**Pull request by wukaiyuan**
First attempt at a permutation shuffle test
* Re-used lots of design from bootstrap.py
* Handles randomized permutation shuffle test
* Handles exact permutation shuffle test

Caveats
* Isn't multithreaded (although the permutation creates a generator which could be made to be multithreaded with some work)
* A lot of redundancy in code (the exact / randomized switching code could be less redundant)
* No warning / limit for a huge dataset for the exact test (there should probably be a maximum size warning / limit)

### CODE REVIEW

**Comment by wukaiyuan** [comment]
Please let me know any suggestions you have to clean up the code

**Comment by spencebeecher** [comment]
This is a great attempt. There is a lot here! Thanks for the submission! 

I am okay to approve this but I do agree on your points above. It would be nice to think about how to merge/simplify the code with what already exists. bootstrapped.py is pretty complicated and could also use simplification (so you have company on this). I think your redundant code is a symptom of the fact that bootstrapped could use simplification (perhaps).

As for this change (since it is in a separate file) i am okay to accept. I would like you to create some unit test cases before merging. Could you add a check/flag for max permutations? Ex-  If the input array is greater than 10k could we limit the number of permutations to 10k?

**Comment by wukaiyuan** [comment]
* I've removed the exact test since it becomes unusable pretty quickly (n! where n is the length of both test and control arrays concatenated together).

* I added the max number of iterations on permutations

* I added unit tests that have passed

If you accept this pull request, here's what I'll work on next:
* Adding the option for one-sided tests (right now it's two-sided by default)

* Refactoring both bootstrap and permutations to re-use functions. This probably means generalizing some of the functions in both into a separate shared utils.py or something similar

* See if it's possible to make randomized permutations multithreaded

**Comment by spencebeecher** [comment]
@wukaiyuan - Thank you so much for the diff. LGTM. I made a few slight changes.

**Pull request closed without merging**
